apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-data-pv
  labels:
    component: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: monitoring-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/monitoring
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "MASTER_NODE_NAME_PLACEHOLDER"
